# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title: A Pretty Jekyllin' Website
author: Michael Gardner
year: 2022
email: Idodevthings@gmail.com
description: >- 
  A Pretty Heckin' Website using Github Pages and Jekyll
keywords: Website, Heckin, Web Development, Jekyll
domain: philotfarnsworth.github.io
url: https://philotfarnsworth.github.io # the base hostname & protocol for your site, e.g. http://example.com
baseurl: /Jekyll-Test # the subpath of your site, e.g. /blog
LinkedIn_url: www.linkedin.com/in/michael-gardner-az 
github_username:  PhiloTFarnsworth

## This tidies up the header a little, but it would be nice to integrate this with our css imports as well, so we only have to
## define fonts in one area.  For now, we'll just pass the file name.
fonts:
  - "LEMONMILK-Light.woff2"
  - "LEMONMILK-LightItalic.woff2"
  - "LEMONMILK-Regular.woff2"
  - "LEMONMILK-RegularItalic.woff2"

## Needed to be fancy and use a custom collection
include: ['_diatribes']
collections:
  diatribes:
    output: true
    permalink: /:path

legal: >-
  This site is for educational purposes only. All images, videos and quotes are not the property of the site
  owner and used with a very tenuous grasp of Fair Use.

# Build settings
# theme: jekyll-theme-hacker
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
